# -*- coding: utf-8 -*-
"""Regression_Housing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qExHsFK4k0yyISJkZhMAw2QAQ41mP3mu
"""

# Import the necessary modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,r2_score,root_mean_squared_error
from sklearn.linear_model import LinearRegression

df = pd.read_csv("Housing_data.csv",
                 parse_dates=['date'])
df.head()

df.info()

df['street'].value_counts()

df.shape

df.drop_duplicates(inplace=True)

df.shape

df.drop(columns=['country'], inplace=True)

df.head()

df['statezip']=df['statezip'].apply(lambda x: int(x.replace('WA ','')))

df.head()

df['statezip'].value_counts()

stnol=[]
stname = []
for i in df['street']:
  x=i.split(' ')
  if not x[0].isnumeric():
    x[0]=x[0].replace('-','')
    print(x[0])
    if x[0].isnumeric():
      stnol.append(int(x[0]))
      stname.append(' '.join(x[1:]))
    else:
      stnol.append(0)
      stname.append(' '.join(x))
  else:
    stnol.append(int(x[0]))
    stname.append(' '.join(x[1:]))

stnol

stname

df['streetname']=stname
df['streetno']=stnol

df.head()

df['streetno'].value_counts()

df['streetname'].value_counts()

le = LabelEncoder()
df[['streetname','city']]=df[['streetname','city']].apply(le.fit_transform)

df.head()

df['date'].value_counts()

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['weekday'] = df['date'].dt.weekday
df['weekno'] = df['date'].dt.isocalendar().week

df.head()

df['month'].value_counts()

df.drop(['date','year','street'],axis=1,inplace= True)

df.head()

df['yr_built'].value_counts()

df['yr_renovated'].value_counts()

df.drop(['yr_renovated'],axis=1,inplace=True)

df['crtage']=df['yr_built'].apply(  lambda x: 2025-x)

df.head()

df.info()

df.describe()

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
scl = ['sqft_above','sqft_lot','sqft_living','sqft_basement','yr_built','statezip',
       'streetno','streetname']
for i in scl:
  df[i] = pd.DataFrame(sc.fit_transform(df[[i]]))

df.head()

df.drop(['statezip','streetno','streetname'],axis=1,inplace=True)

y = df.iloc[:,0]
X = df.iloc[:,1:]

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,
                                                    random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

reg = LinearRegression()
reg.fit(X_train,y_train)

y_pred = reg.predict(X_test)
print('Mean Absolute Error:', mean_absolute_error(y_test, y_pred))
print('R2 Score:', r2_score(y_test, y_pred))
print('Root Mean Squared Error:', root_mean_squared_error(y_test, y_pred))

from sklearn.tree import DecisionTreeRegressor

reg1=DecisionTreeRegressor(random_state=2021)
reg1.fit(X_train,y_train)

y_pred1 = reg1.predict(X_test)
print('Mean Absolute Error:', mean_absolute_error(y_test, y_pred1))
print('R2 Score:', r2_score(y_test, y_pred1))
print('Root Mean Squared Error:', root_mean_squared_error(y_test, y_pred1))

depth_range = [3,4,5,6,7,8,9]
minsplit_range = [5,10,20,25,30]
minleaf_range = [5,10,15]

parameters = dict(max_depth=depth_range,
                  min_samples_split=minsplit_range,
                  min_samples_leaf=minleaf_range)

from sklearn.model_selection import KFold
kfold = KFold(n_splits=5, random_state=2021,
                        shuffle=True)

from sklearn.model_selection import GridSearchCV
clf = DecisionTreeRegressor(random_state=2021)
cv = GridSearchCV(clf, param_grid=parameters,
                  cv=kfold,scoring='r2',verbose=2)

cv.fit(X_train,y_train)

results_df = pd.DataFrame(cv.cv_results_  )
results_df

# Best Parameters
print(cv.best_params_)

print(cv.best_score_)

from sklearn.ensemble import RandomForestRegressor

reg2=RandomForestRegressor(random_state=2021)
reg2.fit(X_train,y_train)

y_pred2 = reg2.predict(X_test)
print('Mean Absolute Error:', mean_absolute_error(y_test, y_pred2))
print('R2 Score:', r2_score(y_test, y_pred2))
print('Root Mean Squared Error:', root_mean_squared_error(y_test, y_pred2))

parameters = dict(max_depth=depth_range,
                  min_samples_split=minsplit_range,
                  min_samples_leaf=minleaf_range,
                  max_features=np.arange(1,11,2))

reg3=RandomForestRegressor(random_state=2021)
cv1 = GridSearchCV(reg3, param_grid=parameters,
                  cv=kfold,scoring='r2',verbose=2)

cv1.fit(X_train,y_train)

results_df = pd.DataFrame(cv1.cv_results_ )
results_df



# Best Parameters
print(cv1.best_params_)

# Best Score
print(cv1.best_score_)